// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdnvAsj31HgOwroU3RO7G-QK178by3eJY',
    appId: '1:444759864301:android:895033bfa62944e4c8ade4',
    messagingSenderId: '444759864301',
    projectId: 'iconnectv2-49c98',
    storageBucket: 'iconnectv2-49c98.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBG1eaoXlZbOPWLv4-WrqpaSLgWH82QZZ0',
    appId: '1:444759864301:ios:51819c8400b22fa6c8ade4',
    messagingSenderId: '444759864301',
    projectId: 'iconnectv2-49c98',
    storageBucket: 'iconnectv2-49c98.appspot.com',
    androidClientId: '444759864301-7df00fm63avjitkrfq8k0scdj0tm3ngg.apps.googleusercontent.com',
    iosClientId: '444759864301-l4gsdteh9b5qgv00m10a35vsl4tplb4a.apps.googleusercontent.com',
    iosBundleId: 'com.example.pallonApp',
  );
}
