import 'package:get/get.dart';

class AppTranslations extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    'en_US': {
      'hello': 'Hello',
      'welcome_message': 'Welcome to our app!',
      'greeting_user': 'Hello, @userName!',
      'products_count': 'You have @count products.',
      'back': 'Back',
      'next': 'Next',
      'close_popup': 'Close Popup',
      'commercial': 'Commercial',
      'retry': 'Retry',
      'no_commercial_items_found': 'No commercial items found.',
      "No content available.": "No content available.",
      "Search in Waseelati...": "Search in Waseelati...",
      "Failed to load image": "Failed to load image",
      "Discover our departments": "Discover our departments",
      "Cars and Vehicles": "Cars and Vehicles",
      "Real Estate": "Real Estate",
      "Electronics": "Electronics",
      "Add New Ads to ": "Add New Ads to ",
      "Search the sections": "Search the sections",
      "What do you want to sell or advertise?": "What do you want to sell or advertise?",
      "Add Your Ads Details": "Add Your Ads Details",
      "Upload Images": "Upload Images",
      "Title": "Title",
      "Call US": "Call US",
      "Submit an application": "Submit an application",
      "Information": "Information",
      "working hours": "working hours",
      "From Sunday to Thursday": "From Sunday to Thursday",
      "From 9 am to 6 pm": "From 9 am to 6 pm",
      "Your opinion": "Your opinion",
      "Your opinion matters to us!": "Your opinion matters to us!",
      "Untitled": "Untitled",
      "Welcome": "Welcome",
      "Price:": "Price:",
      "What's App": "What's App",
      "Commercial Ads": "Commercial Ads",
      "My Account": "My Account",
      "My ads": "My ads",
      "Edit Product": "Edit Product",
      "Add New Images": "Add New Images",
      "Contact Number": "Contact Number",
      "Please enter a contact number": "Please enter a contact number",
      "Address": "Address",
      "You Don't Have Any Ads": "You Don't Have Any Ads",
      "My favorite Ads": "My favorite Ads",
      "You have no favorite ads yet.": "You have no favorite ads yet.",
      "Edit": "Edit",
      "Delete": "Delete",
      "My Search History": "My Search History",
      "No search history found.": "No search history found.",
      "Confirm Deletion": "Confirm Deletion",
      "Cancel": "Cancel",
      "Views": "Views",
      "Activity": "Activity",
      "Favourite Ads": "Favourite Ads",
      "Search History": "Search History",
      "View Unread Notifications Only": "View Unread Notifications Only",
      "No unread notifications": "No unread notifications",
      "No notifications": "No notifications",
      "No additional information available": "No additional information available",
      "Description": "Description",
      "Unknown User": "Unknown User",
      "Location on Map": "Location on Map",
      "No specific address available": "No specific address available",
      "We don't have any Ads Here": "We don't have any Ads Here",
      "Filter Options": "Filter Options",
      "Apply Filters": "Apply Filters",
      "Owner": "Owner",
      "Seller data not available.": "Seller data not available.",
      "This seller has no products yet.": "This seller has no products yet.",
      "Account Mangement": "Account Mangement",
      "Account management": "Account management",
      "Logout": "Logout",
      "Save Changes": "Save Changes",
      "Failed to retrieve products: Unexpected response format.": "Failed to retrieve products: Unexpected response format.",
      "Please log in to view your products.": "Please log in to view your products.",
      "Validation Error', 'Please fill all required fields.": "Validation Error', 'Please fill all required fields.",
      "Call": "Call",
      "Dear Guest": "Dear Guest",
      "Your feedback helps us develop our services.": "Your feedback helps us develop our services.",
      "Tell us your opinion...": "Tell us your opinion...",
      "Send": "Send",
      "Verifying code...": "Verifying code...",
      "Verified successfully!": "Verified successfully!",
      "Code verification failed. Please try again.": "Code verification failed. Please try again.",
      "Welcome back!": "Welcome back!",
      "Didn't receive the code?": "Didn't receive the code?",
      "Enter the code sent to your phone": "Enter the code sent to your phone",
      "verification": "verification",
      "rebroadcast": "rebroadcast",
      "Phone Number": "Phone Number",
      "Sorry Try Again": "Sorry Try Again",
      "By using the Wasilati app, you agree to the Terms of Use and Privacy Policy.": "By using the Wasilati app, you agree to the Terms of Use and Privacy Policy.",
      "Login": "Login",
      "Enter mobile phone number": "Enter mobile phone number",
      "Please enter a correct and active phone number on WhatsApp so that you can receive the verification code.": "Please enter a correct and active phone number on WhatsApp so that you can receive the verification code.",
      "Start now... your first step into a world of opportunities.": "Start now... your first step into a world of opportunities.",
      "City": "City",
      "Set More Details": "Set More Details",
      "Continue to Ad Creation": "Continue to Ad Creation",
      "Set Details": "Set Details",
      "Please select a city": "Please select a city",
      "Jobs": "Jobs",
      "Services and Equipment": "Services and Equipment",
      "Furniture": "Furniture",
      "Fashion, Beauty & Kids": "Fashion, Beauty & Kids",
      "Contracting": "Contracting",
      "more": "more",
      "all": "all",
      "price": "price",
      "Home": "Home",
      "Add your ad": "Add your ad",
      "Similar ads": "Similar ads",
      "Map": "Map",
      "More": "More",
      "(Optinal)": "(Optinal)",
      "phone number": "phone number",
      "Contact: +96522248493": "Contact: +96522248493",
      "WhatsApp: +96598061962-+96567040589": "WhatsApp: +96598061962-+96567040589",
      "the site": "the site",
      "Kuwait - Al-Farawiyya - Habib Al-Munawar Street - Block 3 - Al-Ittihad Complex - 3rd Floor - Office 9": "Kuwait - Al-Farawiyya - Habib Al-Munawar Street - Block 3 - Al-Ittihad Complex - 3rd Floor - Office 9",
      "Contact the advertiser": "Contact the advertiser",
      "Request the advertiser's number": "Request the advertiser's number",
      "Warning: Additional charges may apply. Please check with the advertiser for details.": "Warning: Additional charges may apply. Please check with the advertiser for details.",
      "See ad details": "See ad details",
      "Your opinion matters to us. Share your opinion with us.": "Your opinion matters to us. Share your opinion with us.",
      "Sales department": "Sales department",
      "Settings": "Settings",
      "Add a suggestion": "Add a suggestion",
      "privacy policy": "privacy policy",
      "terms of use": "terms of use",
      "Edit Account": "Edit Account",
      "Information Account": "Information Account",
      "Full Name": "Full Name",
      "Enter Full Name": "Enter Full Name",
      "Please enter your full name": "Please enter your full name",
      "Email": "Email",
      "Enter Email": "Enter Email",
      "Please enter your email": "Please enter your email",
      "Please enter a valid email address": "Please enter a valid email address",
      "Please Enter Your Phone Number": "Please Enter Your Phone Number",
      "Gender": "Gender",
      "Male": "Male",
      "Female": "Female",
      "Please select your gender": "Please select your gender",
      "BirthDate": "BirthDate",
      "Enter BirthDate": "Enter BirthDate",
      "Please enter your birth date": "Please enter your birth date",
      "Account Type": "Account Type",
      "Personal use": "Personal use",
      "For non-commercial use, suitable for individuals wishing to buy and sell some personal items.": "For non-commercial use, suitable for individuals wishing to buy and sell some personal items.",
      "Save Data": "Save Data",
      "We are here to help you. Contact us via any of the following methods:": "We are here to help you. Contact us via any of the following methods:",
      "For general inquiries": "For general inquiries",
      "Dail": "Dail",
      "Available from Sunday to Thursday from 9 am to 5 pm": "Available from Sunday to Thursday from 9 am to 5 pm",
      "Send your message to us": "Send your message to us",
      "message": "message",
      "Enter Your Message": "Enter Your Message",
      "Please Enter Your Message": "Please Enter Your Message",
      "Send Message": "Send Message",
      "Setting App": "Setting App",
      "Choose the language": "Choose the language",
      "English": "English",
      "Click here to Choose": "Click here to Choose",
      "Arabic": "Arabic",
      "Add New Ads": "Add New Ads",
      "Please Choose Category": "Please Choose Category",
      "Login Or Create Account": "Login Or Create Account",
      "By using Wasilati application, you agree to the Terms of Use and Privacy Policy.": "By using Wasilati application, you agree to the Terms of Use and Privacy Policy.",
      "Confirm Phone Number": "Confirm Phone Number",
      "Please enter the verification code sent to your phone.": "Please enter the verification code sent to your phone.",
      "verification code": "verification code",
      "Confirm": "Confirm",
      "Choose From Sub Category": "Choose From Sub Category",
      "Tap to add photos": "Tap to add photos",
      "Please enter a title": "Please enter a title",
      "Please enter the price": "Please enter the price",
      "Details": "Details",
      "Please enter some details": "Please enter some details",
      "Please enter an address": "Please enter an address",
      "Submit Ad": "Submit Ad",
      "Your Ads": "Your Ads",
      "Commercial Products": "Commercial Products",
      "About US": "About US",
      "Service advertisements": "Service advertisements",
      "View Profile": "View Profile",
      "Language": "Language",
      "Help": "Help",
      "Verify": "Verify",
      "Your opinion matters to us":"Your opinion matters to us",
      "Service Advertisements":"Service Advertisements",
      "Didn't receive code? Resend": "Didn't receive code? Resend",
      "Enter mobile number": "Enter mobile number",
      "(Change)": "(Change)",
      "commercials": "commercials",
      "Notification": "Notification",
      "You Don't have any notification": "You Don't have any notification",
      "View Notification un read": "View Notification un read",
      "Don't Have Any Favorite Ads": "Don't Have Any Favorite Ads",
      "My Favorite Search": "My Favorite Search",
      "Don't Have Any Search Favourite": "Don't Have Any Search Favourite",
      "What'sApp": "What'sApp",
      "Contanio to Waselatii": "Contanio to Waselatii",
      "Choose a help topic": "Choose a help topic",
      "Select a topic": "Select a topic",
      "Your opinion matters! Share your rating with us.": "Your opinion matters! Share your rating with us.",
      "View Details": "View Details",
      "Write your suggestion here...": "Write your suggestion here...",
      "Contact our sales team for more services.": "Contact our sales team for more services.",
      "Classifieds": "Classifieds",
      "Waselatii": "Waselatii",
      "Privacy Policy for Wasilati Website and Application": "Privacy Policy for Wasilati Website and Application",
      "Commercial banners": "Commercial banners",
      "Electronic marketing": "Electronic marketing",
      "Design digital banners that increase the value of your advertisement and its spread.": "Design digital banners that increase the value of your advertisement and its spread.",
      "Managing accounts and creating integrated campaigns on social media platforms": "Managing accounts and creating integrated campaigns on social media platforms",
      "Post your ad now at the lowest cost and start attracting customers today.": "Post your ad now at the lowest cost and start attracting customers today.",
      "Designing your commercial increases the value of your relationship and increases its spread.": "Designing your commercial increases the value of your relationship and increases its spread.",
      "Have a suggestion? Share it with us!": "Have a suggestion? Share it with us!",
      "We are always striving to develop and your suggestion may be a reason to improve everyone's experience.": "We are always striving to develop and your suggestion may be a reason to improve everyone's experience.",
      "App Version 1.0.0": "App Version 1.0.0",
      "No topic selected.": "No topic selected.",
      "Selected Topic": "Selected Topic",
      "You Should Login Click Here To Login or Sign up": "You Should Login Click Here To Login or Sign up",
      "Commercial":"Commercial",
      "Notifications":"Notifications",
      "I Look at":"I Look at",
      "Next":"Next",
      "Back":"Back",
      "Close Popup":"Close Popup",
      "No products found matching the selected filters.":"No products found matching the selected filters.",
      "WhatApp":"WhatApp",
      "You Should be Login First":"You Should be Login First",
      "Add New Ads to":"Add New Ads to"
    },
    'ar_DZ': {
      "Add New Ads to":"اضافة اعلانات جديدة الى",
      "You Should be Login First":"يجب عليك تسجيل الدخول أولاً",
      "WhatApp":"واتس",
      "No products found matching the selected filters.":"لم يتم العثور على أي منتجات تطابق المرشحات المحددة.",
      "Next":"التالي",
      "Back":"السابق",
      "Close Popup":"اغلاق النافذة",
      "I Look at":"يمكنك النظر ايضا علي",
      "Notifications":"مركز الاشعارات",
      'hello': 'مرحبا',
      "Service Advertisements":"إعلانات الخدمة",
      "Commercial":"تجاري",
      'welcome_message': 'أهلاً بك في تطبيقنا!',
      'greeting_user': 'أهلاً بك يا @userName!',
      'products_count': 'لديك @count منتجات.',
      'back': 'رجوع',
      'next': 'التالي',
      'close_popup': 'إغلاق النافذة',
      'commercial': 'إعلانات',
      'retry': 'إعادة المحاولة',
      'no_commercial_items_found': 'لم يتم العثور على إعلانات تجارية.',
      "No content available.": "لا يوجد محتوى متاح.",
      "Search in Waseelati...": "ابحث في وصلتي...",
      "Failed to load image": "فشل في تحميل الصورة",
      "Discover our departments": "اكتشف أقسامنا",
      "Cars and Vehicles": "سيارات ومركبات",
      "Real Estate": "عقارات",
      "Electronics": "إلكترونيات",
      "Add New Ads to ": "أضف إعلانات جديدة إلى ",
      "Search the sections": "البحث في الأقسام",
      "What do you want to sell or advertise?": "ماذا تريد أن تبيع أو تعلن عنه؟",
      "Add Your Ads Details": "أضف تفاصيل إعلانك",
      "Upload Images": "تحميل الصور",
      "Title": "العنوان",
      "Call US": "اتصل بنا",
      "Submit an application": "تقديم طلب",
      "Information": "معلومات",
      "working hours": "ساعات العمل",
      "From Sunday to Thursday": "من الأحد إلى الخميس",
      "From 9 am to 6 pm": "من 9 صباحاً إلى 6 مساءً",
      "Your opinion": "رأيك",
      "Your opinion matters to us!": "رأيك يهمنا!",
      "Untitled": "بدون عنوان",
      "Welcome": "مرحباً",
      "Price:": "السعر:",
      "What's App": "واتساب",
      "Commercial Ads": "إعلانات تجارية",
      "My Account": "حسابي",
      "My ads": "إعلاناتي",
      "Edit Product": "تعديل المنتج",
      "Add New Images": "أضف صور جديدة",
      "Contact Number": "رقم التواصل",
      "Please enter a contact number": "الرجاء إدخال رقم تواصل",
      "Address": "العنوان",
      "You Don't Have Any Ads": "ليس لديك أي إعلانات",
      "My favorite Ads": "إعلاناتي المفضلة",
      "You have no favorite ads yet.": "ليس لديك أي إعلانات مفضلة بعد.",
      "Edit": "تعديل",
      "Delete": "حذف",
      "My Search History": "سجل البحث الخاص بي",
      "No search history found.": "لم يتم العثور على سجل بحث.",
      "Confirm Deletion": "تأكيد الحذف",
      "Cancel": "إلغاء",
      "Views": "المشاهدات",
      "Activity": "النشاط",
      "Favourite Ads": "الإعلانات المفضلة",
      "Search History": "سجل البحث",
      "View Unread Notifications Only": "عرض الإشعارات غير المقروءة فقط",
      "No unread notifications": "لا توجد إشعارات غير مقروءة",
      "No notifications": "لا توجد إشعارات",
      "No additional information available": "لا توجد معلومات إضافية متاحة",
      "Description": "الوصف",
      "Unknown User": "مستخدم غير معروف",
      "Location on Map": "الموقع على الخريطة",
      "No specific address available": "لا يوجد عنوان محدد متاح",
      "We don't have any Ads Here": "ليس لدينا أي إعلانات هنا",
      "Filter Options": "خيارات الفلترة",
      "Apply Filters": "تطبيق الفلاتر",
      "Owner": "المالك",
      "Seller data not available.": "بيانات البائع غير متوفرة.",
      "This seller has no products yet.": "لا يوجد لهذا البائع أي منتجات بعد.",
      "Account Mangement": "إدارة الحساب",
      "Account management": "إدارة الحساب",
      "Logout": "تسجيل الخروج",
      "Save Changes": "حفظ التغييرات",
      "Failed to retrieve products: Unexpected response format.": "فشل في استرداد المنتجات: تنسيق استجابة غير متوقع.",
      "Please log in to view your products.": "الرجاء تسجيل الدخول لعرض منتجاتك.",
      "Validation Error', 'Please fill all required fields.": "خطأ في التحقق', 'الرجاء ملء جميع الحقول المطلوبة.",
      "Call": "اتصال",
      "Dear Guest": "عزيزي الضيف",
      "Your feedback helps us develop our services.": "ملاحظاتك تساعدنا في تطوير خدماتنا.",
      "Tell us your opinion...": "أخبرنا برأيك...",
      "Send": "إرسال",
      "Verifying code...": "جاري التحقق من الرمز...",
      "Verified successfully!": "تم التحقق بنجاح!",
      "Code verification failed. Please try again.": "فشل التحقق من الرمز. الرجاء المحاولة مرة أخرى.",
      "Welcome back!": "أهلاً بعودتك!",
      "Didn't receive the code?": "لم تستلم الرمز؟",
      "Enter the code sent to your phone": "أدخل الرمز المرسل إلى هاتفك",
      "verification": "التحقق",
      "rebroadcast": "إعادة الإرسال",
      "Phone Number": "رقم الهاتف",
      "Sorry Try Again": "عذراً حاول مرة أخرى",
      "By using the Wasilati app, you agree to the Terms of Use and Privacy Policy.": "باستخدام تطبيق وصلتي، أنت توافق على شروط الاستخدام وسياسة الخصوصية.",
      "Login": "تسجيل الدخول",
      "Enter mobile phone number": "أدخل رقم الهاتف المحمول",
      "Please enter a correct and active phone number on WhatsApp so that you can receive the verification code.": "الرجاء إدخال رقم هاتف صحيح ونشط على واتساب لتتمكن من استلام رمز التحقق.",
      "Start now... your first step into a world of opportunities.": "ابدأ الآن... خطوتك الأولى نحو عالم من الفرص.",
      "City": "المدينة",
      "Set More Details": "تحديد المزيد من التفاصيل",
      "Continue to Ad Creation": "المتابعة لإنشاء الإعلان",
      "Set Details": "تحديد التفاصيل",
      "Please select a city": "الرجاء اختيار مدينة",
      "Jobs": "وظائف",
      "Services and Equipment": "خدمات ومعدات",
      "Furniture": "أثاث",
      "Fashion, Beauty & Kids": "أزياء، جمال وأطفال",
      "Contracting": "مقاولات",
      "more": "المزيد",
      "all": "الكل",
      "price": "السعر",
      "Home": "الرئيسية",
      "Add your ad": "أضف إعلانك",
      "Similar ads": "إعلانات مشابهة",
      "Map": "الخريطة",
      "More": "المزيد",
      "(Optinal)": "(اختياري)",
      "phone number": "رقم الهاتف",
      "Contact: +96522248493": "للتواصل: +96522248493",
      "WhatsApp: +96598061962-+96567040589": "واتساب: +96598061962-+96567040589",
      "the site": "الموقع",
      "Kuwait - Al-Farawiyya - Habib Al-Munawar Street - Block 3 - Al-Ittihad Complex - 3rd Floor - Office 9": "الكويت - الفروانية - شارع حبيب المناور - قطعة 3 - مجمع الاتحاد - الدور الثالث - مكتب 9",
      "Contact the advertiser": "تواصل مع المعلن",
      "Request the advertiser's number": "طلب رقم المعلن",
      "Warning: Additional charges may apply. Please check with the advertiser for details.": "تحذير: قد يتم تطبيق رسوم إضافية. يرجى التحقق من المعلن للحصول على التفاصيل.",
      "See ad details": "شاهد تفاصيل الإعلان",
      "Your opinion matters to us. Share your opinion with us.": "رأيك يهمنا. شاركنا برأيك.",
      "Sales department": "قسم المبيعات",
      "Settings": "الإعدادات",
      "Add a suggestion": "إضافة اقتراح",
      "privacy policy": "سياسة الخصوصية",
      "terms of use": "شروط الاستخدام",
      "Edit Account": "تعديل الحساب",
      "Information Account": "معلومات الحساب",
      "Full Name": "الاسم الكامل",
      "Enter Full Name": "أدخل الاسم الكامل",
      "Please enter your full name": "الرجاء إدخال اسمك الكامل",
      "Email": "البريد الإلكتروني",
      "Enter Email": "أدخل البريد الإلكتروني",
      "Please enter your email": "الرجاء إدخال بريدك الإلكتروني",
      "Please enter a valid email address": "الرجاء إدخال عنوان بريد إلكتروني صحيح",
      "Please Enter Your Phone Number": "الرجاء إدخال رقم هاتفك",
      "Gender": "الجنس",
      "Male": "ذكر",
      "Female": "أنثى",
      "Please select your gender": "الرجاء اختيار جنسك",
      "BirthDate": "تاريخ الميلاد",
      "Enter BirthDate": "أدخل تاريخ الميلاد",
      "Please enter your birth date": "الرجاء إدخال تاريخ ميلادك",
      "Account Type": "نوع الحساب",
      "Personal use": "استخدام شخصي",
      "For non-commercial use, suitable for individuals wishing to buy and sell some personal items.": "للاستخدام غير التجاري، مناسب للأفراد الراغبين في شراء وبيع بعض الأغراض الشخصية.",
      "Save Data": "حفظ البيانات",
      "We are here to help you. Contact us via any of the following methods:": "نحن هنا لمساعدتك. تواصل معنا عبر أي من الطرق التالية:",
      "For general inquiries": "للاستفسارات العامة",
      "Dail": "اتصال",
      "Available from Sunday to Thursday from 9 am to 5 pm": "متاح من الأحد إلى الخميس من 9 صباحًا حتى 5 مساءً",
      "Send your message to us": "أرسل رسالتك إلينا",
      "message": "رسالة",
      "Enter Your Message": "أدخل رسالتك",
      "Please Enter Your Message": "الرجاء إدخال رسالتك",
      "Send Message": "إرسال الرسالة",
      "Setting App": "إعدادات التطبيق",
      "Choose the language": "اختر اللغة",
      "English": "الإنجليزية",
      "Click here to Choose": "اضغط هنا للاختيار",
      "Arabic": "العربية",
      "Add New Ads": "أضف إعلانات جديدة",
      "Please Choose Category": "الرجاء اختيار الفئة",
      "Login Or Create Account": "تسجيل الدخول أو إنشاء حساب",
      "By using Wasilati application, you agree to the Terms of Use and Privacy Policy.": "باستخدام تطبيق وصلتي، أنت توافق على شروط الاستخدام وسياسة الخصوصية.",
      "Confirm Phone Number": "تأكيد رقم الهاتف",
      "Please enter the verification code sent to your phone.": "الرجاء إدخال رمز التحقق المرسل إلى هاتفك.",
      "verification code": "رمز التحقق",
      "Confirm": "تأكيد",
      "Choose From Sub Category": "اختر من الفئة الفرعية",
      "Tap to add photos": "اضغط لإضافة صور",
      "Please enter a title": "الرجاء إدخال عنوان",
      "Please enter the price": "الرجاء إدخال السعر",
      "Details": "التفاصيل",
      "Please enter some details": "الرجاء إدخال بعض التفاصيل",
      "Please enter an address": "الرجاء إدخال عنوان",
      "Submit Ad": "إرسال الإعلان",
      "Your Ads": "إعلاناتك",
      "Commercial Products": "المنتجات التجارية",
      "About US": "عنا",
      "Service advertisements": "إعلانات الخدمات",
      "View Profile": "عرض الملف الشخصي",
      "Language": "اللغة",
      "Help": "المساعدة",
      "Verify": "تحقق",
      "Didn't receive code? Resend": "لم تستلم الرمز؟ إعادة الإرسال",
      "Enter mobile number": "أدخل رقم الجوال",
      "(Change)": "(تغيير)",
      "commercials": "إعلانات تجارية",
      "Notification": "الإشعارات",
      "You Don't have any notification": "ليس لديك أي إشعارات",
      "View Notification un read": "عرض الإشعارات غير المقروءة",
      "Don't Have Any Favorite Ads": "ليس لديك إعلانات مفضلة",
      "My Favorite Search": "بحثي المفضل",
      "Don't Have Any Search Favourite": "ليس لديك بحث مفضل",
      "What'sApp": "واتساب",
      "Contanio to Waselatii": "المتابعة إلى وصلتي",
      "Choose a help topic": "اختر موضوع مساعدة",
      "Select a topic": "حدد موضوعًا",
      "Your opinion matters! Share your rating with us.": "رأيك يهمنا! شارك تقييمك معنا.",
      "View Details": "عرض التفاصيل",
      "Write your suggestion here...": "اكتب اقتراحك هنا...",
      "Contact our sales team for more services.": "تواصل مع فريق المبيعات لدينا للحصول على المزيد من الخدمات.",
      "Classifieds": "إعلانات مبوبة",
      "Waselatii": "وصلتي",
      "Privacy Policy for Wasilati Website and Application": "سياسة الخصوصية لموقع وتطبيق وصلتي",
      "Commercial banners": "اللافتات التجارية",
      "Electronic marketing": "التسويق الإلكتروني",
      "Design digital banners that increase the value of your advertisement and its spread.": "تصميم لافتات رقمية تزيد من قيمة إعلانك وانتشاره.",
      "Managing accounts and creating integrated campaigns on social media platforms": "إدارة الحسابات وإنشاء حملات متكاملة على منصات التواصل الاجتماعي",
      "Post your ad now at the lowest cost and start attracting customers today.": "انشر إعلانك الآن بأقل تكلفة وابدأ في جذب العملاء اليوم.",
      "Designing your commercial increases the value of your relationship and increases its spread.": "تصميم إعلانك التجاري يزيد من قيمة علاقتك ويزيد من انتشاره.",
      "Have a suggestion? Share it with us!": "لديك اقتراح؟ شاركه معنا!",
      "We are always striving to develop and your suggestion may be a reason to improve everyone's experience.": "نحن نسعى دائمًا للتطوير وقد يكون اقتراحك سببًا في تحسين تجربة الجميع.",
      "App Version 1.0.0": "إصدار التطبيق 1.0.0",
      "No topic selected.": "لم يتم اختيار موضوع.",
      "Selected Topic": "الموضوع المختار",
      "Your opinion matters to us":"رايك يهمنا",
      "You Should Login Click Here To Login or Sign up": "يجب عليك تسجيل الدخول. اضغط هنا لتسجيل الدخول أو الاشتراك",
    },
  };
}